/* SALGA direct buyer chat widget. Kept separate from AI Customer Care. */
(function(){
  const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");
  const session=()=>{try{return JSON.parse(localStorage.getItem("session")||"null")}catch{return null}};
  const api=async body=>{const s=session();const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json",...(s?.access_token?{Authorization:"Bearer "+s.access_token}:{})},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Chat request failed.");return d};
  const adminApi=async()=>{const s=session();const r=await fetch("/api/chat-admin",{method:"POST",headers:{"Content-Type":"application/json",...(s?.access_token?{Authorization:"Bearer "+s.access_token}:{})},body:JSON.stringify({})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Unable to start admin chat.");return d};
  let active=null;
  function open(){
    if(!document.getElementById("salgaChatWidget")){
      const w=document.createElement("div");w.id="salgaChatWidget";w.style="position:fixed;right:12px;bottom:12px;width:min(390px,calc(100vw - 24px));background:#fff;border-radius:16px;box-shadow:0 10px 35px #0003;z-index:9999;overflow:hidden;border:1px solid #d6dde1";
      w.innerHTML='<div style="background:#075e54;color:#fff;padding:14px;font-weight:800">SALGA Messages <button id="scwClose" style="float:right;background:#fff;color:#075e54;padding:5px 9px">×</button></div><div style="padding:12px"><button id="scwAdmin" style="background:#075e54;color:#fff;border:0;border-radius:8px;padding:9px;margin-bottom:8px">Chat SALGA Administration</button><div id="scwList"></div><div id="scwMsgs" style="height:240px;overflow:auto;background:#f4f7f8;padding:8px;border-radius:9px;margin:8px 0"></div><div style="display:flex;gap:7px"><input id="scwInput" placeholder="Write a message..." style="flex:1;padding:10px;border:1px solid #d6dde1;border-radius:8px"><button id="scwSend" style="background:#0b806f;color:#fff;border:0;border-radius:8px;padding:10px 13px">Send</button></div></div>';
      document.body.appendChild(w);scwClose.onclick=()=>w.remove();scwSend.onclick=send;scwAdmin.onclick=async()=>{try{const d=await adminApi();openConversation(d.conversation.id)}catch(e){alert(e.message)}};
    }
    load();
  }
  async function load(){const list=scwList,msgs=scwMsgs;try{const d=await api({action:"conversations"});list.innerHTML=(d.conversations||[]).map(c=>`<button data-id="${esc(c.id)}" style="margin:3px;padding:8px;border:0;border-radius:8px;background:#e8f2f0">${esc(c.name||"Conversation")}</button>`).join("")||'<div style="color:#68727d">No business conversations yet.</div>';list.querySelectorAll("button").forEach(b=>b.onclick=()=>openConversation(b.dataset.id));msgs.innerHTML='<div style="color:#68727d">Select a conversation.</div>';}catch(e){list.innerHTML=`<div style="color:#8b1e1e">${esc(e.message)}</div>`}}
  async function openConversation(id){active=id;const d=await api({action:"messages",conversation_id:id});scwMsgs.innerHTML=(d.messages||[]).map(m=>`<div style="padding:8px;background:#fff;border-radius:8px;margin-bottom:6px"><b>${esc(m.sender_role||"User")}</b><div>${esc(m.message||"")}</div></div>`).join("")||'<div style="color:#68727d">No messages yet.</div>';scwMsgs.scrollTop=scwMsgs.scrollHeight;}
  async function send(){const text=scwInput.value.trim();if(!active||!text)return;await api({action:"send",conversation_id:active,message:text});scwInput.value="";openConversation(active)}
  window.SALGAChat={open,openBusiness:async id=>{if(!session()?.access_token)return alert("Please log in to your existing buyer account first.");const d=await api({action:"start",business_id:id});open();openConversation(d.conversation.id)},openAdmin:async()=>{if(!session()?.access_token)return alert("Please log in to your existing buyer account first.");const d=await adminApi();open();openConversation(d.conversation.id)}};
})();
