(function(){"use strict";
const esc=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const sessionToken=()=>{try{return typeof session!=="undefined"?session?.access_token:null}catch(_){return null}};
async function avatarRequest(url,options={}){const h={...(options.headers||{})};const t=sessionToken();if(t)h.Authorization="Bearer "+t;const r=await fetch(url,{...options,headers:h});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch(_){throw Error("Invalid server response.")}if(!r.ok)throw Error(d.error||"Request failed");return d;}
function card(title,role){const id=role==="seller"?"salgaSellerAvatarCard":"salgaBuyerAvatarCard";if(document.getElementById(id))return document.getElementById(id);const host=document.createElement("div");host.id=id;host.className="panel";host.innerHTML=`<div class="row" style="align-items:center"><div id="${id}Preview" style="width:72px;height:72px;border-radius:50%;overflow:hidden;background:#e8ecef;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:800;color:#075e54">?</div><div><h3 style="margin:0">${title}</h3><div class="muted">${role==="seller"?"Use your face or business logo as your public seller picture.":"Add a profile picture so other marketplace users can recognize you."}</div></div></div><div class="field"><label>Profile picture</label><input id="${id}Input" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><div class="file-help">JPG, PNG, WEBP or GIF · maximum 5 MB</div></div><button class="btn" id="${id}Button" type="button">Upload picture</button><div id="${id}Status" class="status"></div>`;return host;}
async function loadOwnAvatar(role){const id=role==="seller"?"salgaSellerAvatarCard":"salgaBuyerAvatarCard";const p=await avatarRequest("/api/profile-avatar");const url=p.profile?.avatar_url;const preview=document.getElementById(id+"Preview");if(preview){preview.innerHTML=url?`<img src="${esc(url)}" alt="Profile picture" style="width:100%;height:100%;object-fit:cover">`:esc((p.profile?.full_name||"?").slice(0,1).toUpperCase());}}
function mountOwnCards(){let meNow=null;try{meNow=typeof me!=="undefined"?me:null}catch(_){}if(!meNow)return;if(meNow.role==="buyer"){const dash=document.getElementById("buyerDashboard");if(dash&&!dash.classList.contains("hidden")){const c=card("My profile picture","buyer");const host=dash.querySelector(".hero");if(host&&!c.parentNode)host.after(c);bind("buyer");}}if(meNow.role==="seller"){const dash=document.getElementById("sellerDashboard");if(dash&&!dash.classList.contains("hidden")){const c=card("Business owner profile picture","seller");const host=dash.querySelector(".hero");if(host&&!c.parentNode)host.after(c);bind("seller");}}}
function bind(role){const id=role==="seller"?"salgaSellerAvatarCard":"salgaBuyerAvatarCard";const input=document.getElementById(id+"Input"),button=document.getElementById(id+"Button"),status=document.getElementById(id+"Status");if(!input||button.dataset.bound)return;button.dataset.bound="1";button.onclick=async()=>{const file=input.files?.[0];if(!file)return alert("Please choose a picture first.");const fd=new FormData();fd.append("avatar",file);button.disabled=true;status.textContent="Uploading...";try{await avatarRequest("/api/profile-avatar",{method:"POST",body:fd});status.textContent="Profile picture updated.";await loadOwnAvatar(role);decorateSellerCards()}catch(e){status.textContent=e.message||"Upload failed."}finally{button.disabled=false}};loadOwnAvatar(role).catch(()=>{});}
async function decorateSellerCards(){const list=Array.isArray(window.products)?window.products:[];document.querySelectorAll("#products .product").forEach(async cardEl=>{if(cardEl.querySelector(".salga-seller-avatar"))return;const b=cardEl.querySelector("button[onclick*='buyProduct']");if(!b)return;const m=(b.getAttribute("onclick")||"").match(/buyProduct\(['\"]([^'\"]+)['\"]\)/);const p=m?list.find(x=>String(x.id)===String(m[1])):null;const bid=p?.business_id||p?.businesses?.id;if(!bid)return;try{const d=await avatarRequest(`/api/public-profile?business_id=${encodeURIComponent(bid)}`);const u=d.owner?.avatar_url;const name=d.owner?.full_name||d.business?.business_name||"Seller";const row=document.createElement("div");row.className="salga-seller-avatar";row.style="display:flex;align-items:center;gap:8px;margin-top:8px";row.innerHTML=`<div style="width:36px;height:36px;border-radius:50%;overflow:hidden;background:#e8ecef;display:flex;align-items:center;justify-content:center;font-weight:800;color:#075e54">${u?`<img src="${esc(u)}" alt="Seller" style="width:100%;height:100%;object-fit:cover">`:esc(name.slice(0,1).toUpperCase())}</div><div><div style="font-weight:700">${esc(name)}</div><div class="muted">Seller on SALGA Digital Mart</div></div>`;cardEl.appendChild(row);}catch(_){} });}
function interceptOldBuy(){document.addEventListener("click",e=>{const b=e.target?.closest?.("button[onclick*='buyProduct']");if(!b)return;const m=(b.getAttribute("onclick")||"").match(/buyProduct\(['\"]([^'\"]+)['\"]\)/);if(!m)return;if(typeof window.requestSalgaDelivery==="function"){e.preventDefault();e.stopImmediatePropagation();window.requestSalgaDelivery(m[1]);}},true);}
function boot(){mountOwnCards();decorateSellerCards();interceptOldBuy();const obs=new MutationObserver(()=>{mountOwnCards();decorateSellerCards()});obs.observe(document.body,{childList:true,subtree:true});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
